version: '3.3'
services:
  web:
    build: .
    ports:
      - '1323:1323'
    volumes:
      - .:/go/src
      - pkg:/go/pkg
    command: realize start
  db:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=password'
    volumes:
      - datadir:/var/lib/mysql
volumes:
  pkg:
  datadir:
