version: '3.3'
services:
  web:
    build: .
    ports:
      - '1323:1323'
      - '8080:8080'
    environment:
      - 'CGO_ENABLED=1'
    volumes:
      - .:/go/src
      - pkg:/go/pkg
    command: realize start
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_DATABASE=dev_db'
    volumes:
      - datadir:/var/lib/mysql
volumes:
  pkg:
  datadir:
