# status: docker-compose exec web sql-migrate status -config=configs/dbconfig.yml -env="local"
# up: docker-compose exec web sql-migrate up -config=configs/dbconfig.yml -env="local"
# down: docker-compose exec web sql-migrate down -limit=1 -config=configs/dbconfig.yml -env="local"
local:
  dialect: mysql
  datasource: ${DB_USER}:${DB_PASSWORD}@tcp(${DB_HOST}:3306)/${DB_NAME}?parseTime=true
  dir: migrations

# まだGAE上から実行できないので、暫定でローカル(ネットワークも違うのでローカルのdockerから叩けないorz)から実行するようにしている(cloud_sql_proxyを噛ませている前提)
development:
  dialect: mysql
  datasource: ${DB_USER}:${DB_PASSWORD}@tcp(${DB_HOST}:3306)/${DB_NAME}?parseTime=true
  dir: migrations
